### ISSUE TITLE
Uncaught Error: watch ENOSPC

### ISSUE THREAD

**Issue by janosimas** [siegelaaron94/atom-build-cmake#2]
[Enter steps to reproduce below:]

Just started atom, don't know why it happened.
The plugin is working fine.

**Atom Version**: 1.6.0
**System**: Ubuntu 14.04.4
**Thrown From**: [build-cmake](https://github.com/siegelaaron94/atom-build-cmake) package, v0.3.1
### Stack Trace

Uncaught Error: watch ENOSPC

```
At events.js:141

Error: watch ENOSPC
  at exports._errnoException (util.js:837:11)
  at FSWatcher.start (fs.js:1247:11)
  at Object.fs.watch (fs.js:1273:11)
  at createFsWatchInstance (/home/jsimas/.atom/packages/build-cmake/node_modules/chokidar/lib/nodefs-handler.js:37:15)
  at setFsWatchListener (/home/jsimas/.atom/packages/build-cmake/node_modules/chokidar/lib/nodefs-handler.js:80:15)
  at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/jsimas/.atom/packages/build-cmake/node_modules/chokidar/lib/nodefs-handler.js:228:14)
  at FSWatcher.NodeFsHandler._handleFile (/home/jsimas/.atom/packages/build-cmake/node_modules/chokidar/lib/nodefs-handler.js:255:21)
  at FSWatcher.<anonymous> (/home/jsimas/.atom/packages/build-cmake/node_modules/chokidar/lib/nodefs-handler.js:473:21)
  at FSReqWrap.oncomplete (fs.js:82:15)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-thrift",
      "atom-debugger",
      "linter",
      "linter-clang",
      "you-complete-me",
      "language-ocaml",
      "language-ini",
      "language-babel",
      "haskell-grammar",
      "switch-header-source"
    ],
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
build, v0.57.0
build-cmake, v0.3.1
build-make, v0.8.0
file-type-icons, v1.0.1
highlight-selected, v0.11.2
language-cmake, v0.1.4
language-cpp14, v0.6.0
language-qtpro, v0.6.0
nuclide, v0.125.0
open-recent, v5.0.0
selection-highlight, v0.1.4
terminal-plus, v0.14.5
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by siegelaaron94** [comment]
In your build dir can you run this to check how many files are there?
find . -type f | wc -l

**Comment by janosimas** [comment]
4152
