### ISSUE TITLE
Can't edit cache

### ISSUE THREAD

**Issue by BenjaminNavarro** [siegelaaron94/atom-build-cmake#36]
When I try to run the edit_cache target on my projects it systematically fails. If I run the same command (cmake --build \<path-to-project\>/build --target edit_cache) from a terminal, it works as expected. 

Here is the error showing up in Atom:

**Atom**: 1.20.1 x64
**Electron**: 1.6.11
**OS**: linux 4.11.12-1-rt13-rt
**Thrown From**: [build](https://github.com/noseglid/atom-build) package 0.69.0

### Stack Trace

Uncaught TypeError: Cannot set property '1' of undefined

```
At /home/idhuser/.atom/packages/build/node_modules/term.js/src/term.js:1939

TypeError: Cannot set property '1' of undefined
    at Terminal.write (/packages/build/node_modules/term.js/src/term.js:1939:55)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
 65x -2:19.7.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:17.2.0 core:move-left (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:17 core:move-right (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.9.0 core:move-up (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.8.0 core:move-left (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.6.0 core:move-right (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.6.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.4.0 core:move-left (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:16.3.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:11.7.0 build:stop (div.terminal)
     -2:08.7.0 platformio-ide-terminal:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:11.5.0 editor:copy-path (div.terminal)
     -0:57.7.0 build:select-active-target (input.hidden-input)
     -0:56 core:confirm (input.hidden-input)
     -0:25.6.0 build:select-active-target (input.hidden-input)
     -0:22.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atom-latex 0.8.2 
atom-typescript 11.0.9 
autocomplete-clang 0.11.3 
autocomplete-cmake 0.3.1 
autocomplete-python 1.10.3 
build 0.69.0 
build-cmake 0.10.2 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
dash 1.7.1 
debug 0.0.1 
doxygen-snippets 0.1.1 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
ink 0.7.6 
intentions 1.1.5 
julia-client 0.6.3 
language-cmake 0.3.0 
language-julia 0.12.0 
language-latex 1.1.1 
language-lua 0.9.11 
language-rust 0.4.12 
latex 0.48.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-lua 1.0.4 
linter-rust 0.8.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.10 
local-settings 0.4.1 
MagicPython 1.0.12 
maximize-panes 0.2.0 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
python-indent 1.1.1 
python-jedi 0.3.8 
python-snippets 1.9.0 
python-tools 0.6.9 
racer 0.20.0 
Remote-FTP 1.1.4 
rust-api-docs-helper 0.5.1 
rustfmt 0.1.3 
script 3.16.0 
split-diff 1.5.1 
todo-show 2.1.0 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by siegelaaron94** [comment]
How exactly would you like this to work? Because the edit_cache is a ncurses based interface. However, if you would like to pass extra settings to CMake your can go to the settings and add them in the 'Custom Cmake Arguments' field.

**Comment by BenjaminNavarro** [comment]
For me, a terminal-like panel showing the ccmake output and that can be interacted with to edit the options would be perfect
